### ISSUE TITLE
Assets version not mentioned on install

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Documentation-SuperUsers#1]
In [upgrading](https://github.com/OpenACalendar/OpenACalendar-Documentation-SuperUsers/blob/master/upgrading.rst#assets-version-and-browser-caching) it's stated that asset version should be set to 1 on a new install - but thats not mentioned in the [install page](http://docs-superusers.openacalendar.org/en/v1.6.x/install.html#let-s-go)

**Comment by jarofgreen** [comment]
So it's set to 1 by default https://github.com/OpenACalendar/OpenACalendar-Web-Core/blob/master/core/php/Config.php#L72

I guess it should really be set to 1 in https://github.com/OpenACalendar/OpenACalendar-Web-Core/blob/master/config.dist.php explicitly- that way, when you come to upgrading and want to increase it it's already there. And then we don't have to add anything to the docs, which keeps them a touch simpler.

**Comment by GregSutcliffe** [comment]
Right, I added it at 2 to my config file after the upgrade to 1.6 but that was a guess - I wasn't aware it defaulted to 1. Putting it in dist and then rewording the increment part of the docs works for me. I can send a patch for the latter if you wish.

**Comment by jarofgreen** [comment]
Added some code - If you had suggestions for the docs that would be great!

**Comment by GregSutcliffe** [comment]
Config update looks good. I can patch the docs, give me a sec
